#!/usr/bin/env bash
set -euo pipefail

: "${AKD_TASK_JSON:?AKD_TASK_JSON is required}"
: "${AKD_WORK_BRANCH:?AKD_WORK_BRANCH is required}"
: "${AKD_BASE_BRANCH:=main}"

if ! command -v gh >/dev/null 2>&1; then
  echo "GitHub CLI is required" >&2
  exit 2
fi

git push --set-upstream origin "$AKD_WORK_BRANCH"

existing="$(gh pr list --head "$AKD_WORK_BRANCH" --base "$AKD_BASE_BRANCH" --json url --jq '.[0].url // empty')"
if [ -n "$existing" ]; then
  echo "$existing"
  exit 0
fi

title="$(echo "$AKD_TASK_JSON" | jq -r '.changeSet.requirementIds[0] // "AKD automated change"')"
summary="$(echo "$AKD_TASK_JSON" | jq -r '[.requirements[].description] | join("\n- ")')"

gh pr create   --base "$AKD_BASE_BRANCH"   --head "$AKD_WORK_BRANCH"   --title "AKD: $title"   --body "Automated AKD delivery.

Requirements:
- $summary

Generated by Auto Keep Doing. Verification is performed in the VERIFY task before delivery."
